#!/bin/bash
# build_app.sh — builds a self-contained FanCooler.app (universal: Intel + Apple Silicon)
# Usage: bash build_app.sh
set -e
PROJECT="$(cd "$(dirname "$0")" && pwd)"
APP="$(dirname "$PROJECT")/FanCooler.app"
echo "Building $APP ..."

# Find Python (for icon generation only)
PYTHON=""
for c in python3 python3.12 python3.11 python3.10 python3.9 python3.8 python3.6; do
    if command -v "$c" &>/dev/null; then PYTHON=$(command -v "$c"); break; fi
done
[ -z "$PYTHON" ] && { echo "ERROR: Python 3 not found"; exit 1; }

# Bundle structure
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

# Compile universal binary launcher (Intel + Apple Silicon)
echo "  Compiling launcher (universal)..."
cc -arch x86_64 -arch arm64 \
   -o "$APP/Contents/MacOS/FanCooler" \
   "$PROJECT/launcher.c" \
   || cc -o "$APP/Contents/MacOS/FanCooler" "$PROJECT/launcher.c"  # fallback single-arch
chmod +x "$APP/Contents/MacOS/FanCooler"

# Copy Python source into bundle
echo "  Copying Python sources into bundle..."
for f in dashboard.py monitor.py menubar.py smc_write.py; do
    [ -f "$PROJECT/$f" ] && cp "$PROJECT/$f" "$APP/Contents/Resources/"
done

# Copy smc_tool (Intel fan control binary — won't run on Apple Silicon, that's ok)
[ -f "$PROJECT/smc_tool" ] && cp "$PROJECT/smc_tool" "$APP/Contents/Resources/"

# Info.plist
cat > "$APP/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>             <string>FanCooler</string>
    <key>CFBundleDisplayName</key>      <string>FanCooler</string>
    <key>CFBundleIdentifier</key>       <string>com.senchabox.fancooler</string>
    <key>CFBundleVersion</key>          <string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleExecutable</key>       <string>FanCooler</string>
    <key>CFBundlePackageType</key>      <string>APPL</string>
    <key>CFBundleSignature</key>        <string>????</string>
    <key>CFBundleIconFile</key>         <string>AppIcon</string>
    <key>NSHighResolutionCapable</key>  <true/>
    <key>NSAppleEventsUsageDescription</key>
        <string>FanCooler uses AppleScript to control fan speed.</string>
</dict>
</plist>
PLIST

# Build icon
echo "  Building icon..."
ICONSET="/tmp/FanCooler_$$.iconset"
mkdir -p "$ICONSET"
"$PYTHON" "$PROJECT/make_icon.py"
for pair in "16:icon_16x16" "32:icon_16x16@2x" "32:icon_32x32" \
            "64:icon_32x32@2x" "128:icon_128x128" "256:icon_128x128@2x" \
            "256:icon_256x256" "512:icon_256x256@2x" "512:icon_512x512" \
            "1024:icon_512x512@2x"; do
    sz="${pair%%:*}"; name="${pair##*:}"
    cp "/tmp/icon_${sz}.png" "$ICONSET/${name}.png"
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
rm -rf "$ICONSET"

# Bundle the menu bar template glyph (generated by make_icon.py above)
[ -f /tmp/fancooler_menubar.png ] && \
    cp /tmp/fancooler_menubar.png "$APP/Contents/Resources/menubar_icon.png"

xattr -cr "$APP"
echo ""
echo "Done! $APP"
echo "Copy this .app to any Mac. Target machine needs Python 3 + packages:"
echo "  pip3 install psutil matplotlib rumps pyobjc-framework-Cocoa"
